sonar.projectKey=Steven01231_SOEN345-Winter2026
sonar.organization=steven01231
sonar.projectName=SOEN345-Winter2026
sonar.projectVersion=1.0

# Sources
sonar.sources=app/src/main
sonar.tests=app/src/test,app/src/androidTest
sonar.java.binaries=app/build/intermediates/javac/debug/classes
sonar.kotlin.binaries=app/build/tmp/kotlin-classes/debug

# Coverage
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

# Exclusions
sonar.exclusions=**/*Test*,**/R.class,**/R$*.class,**/BuildConfig.*,**/Manifest*.*
sonar.coverage.exclusions=**/*Test*,**/R.class,**/R$*.class,**/BuildConfig.*,**/Manifest*.*

# Encoding
sonar.sourceEncoding=UTF-8
